name: sync-images🐳
on:
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4.3.0
      
      - name: Read Config Yaml
        uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: './config.yaml'

      - name: Aggregate Images
        id: aggregate
        run: | 
          images=()
          env_vars=$(env | grep '^source__images__')
          while IFS='=' read -r key value; do
            images+=("$value")
          done <<< "$env_vars"
          echo "source__images=${images[*]}" >> $GITHUB_ENV

      - name: Pull And Rename Images 
        run: |
          # Extract the array from the environment variable
          images=$(echo ${{ env.source__images }} | tr -d '[]' | tr ',' ' ')

          new_images=()
          for image in $images; do
            echo "=== Pulling image: $image ==="
            docker pull $image
            
            new_tag="${{ env.target__host }}/${{ env.target__namespace }}/${image#*/}"
            new_images+=("$new_tag")
            echo "=== Rename to: $new_tag ==="
            docker tag $image $new_tag
          done
          echo "target__images=${new_images[*]}" >> $GITHUB_ENV

        
